//! AngelScript Core Types
//!
//! This crate provides the core type definitions shared between the FFI
//! and compiler crates in the AngelScript implementation.
//!
//! ## Core Types
//!
//! - [`TypeHash`]: Deterministic 64-bit hash for type identity
//! - [`DataType`]: Complete type with modifiers (const, handle, reference)
//! - [`TypeDef`]: Type definitions (primitives, classes, interfaces, enums, funcdefs)
//! - [`FunctionDef`]: Function definitions with complete signatures
//! - [`ExprInfo`]: Expression type checking results
//! - [`TypeBehaviors`]: Lifecycle behaviors for types
//! - [`FfiExpr`]: Owned expressions for FFI default arguments
//! - [`Span`]: Source location tracking for error reporting
//!
//! ## Registry Entry Types
//!
//! - [`TypeEntry`]: Unified enum for type storage in registry
//! - [`ClassEntry`], [`EnumEntry`], [`InterfaceEntry`], [`FuncdefEntry`]: Type entries
//! - [`FunctionEntry`]: Function storage with implementation
//! - [`TypeSource`], [`FunctionSource`]: Origin tracking (FFI vs script)
//!
//! ## Operators
//!
//! - [`BinaryOp`]: Binary operators (arithmetic, logical, comparison)
//! - [`UnaryOp`]: Unary operators (negation, not, increment)
//! - [`Operator`]: Operator enum for proc-macro attributes
//!
//! ## Traits
//!
//! - [`Any`]: Trait for types registrable with AngelScript
//!
//! ## Error Types
//!
//! - [`AngelScriptError`]: Unified error type for all phases
//! - [`LexError`]: Lexer/tokenization errors
//! - [`ParseError`]: Parser errors with [`ParseErrorKind`]
//! - [`ParseErrors`]: Collection of parse errors
//! - [`RegistrationError`]: Type/function registration errors
//! - [`CompilationError`]: Semantic analysis and compilation errors
//! - [`RuntimeError`]: Execution/runtime errors

pub mod ops;
pub mod type_hash;
mod data_type;
mod type_def;
mod function_def;
mod expr_info;
mod behaviors;
mod ffi_expr;
mod span;
mod error;

// New types for unified type registry
mod ids;
mod operator;
mod any;
pub mod entries;

// Native function / VM runtime types (moved from angelscript-registry)
pub mod native_fn;
pub mod native_error;
pub mod list_buffer;
pub mod template;
pub mod any_type;

// Metadata types for proc-macros
pub mod meta;

// TypeHash and related
pub use type_hash::{hash_constants, primitives, TypeHash};

// Operators
pub use ops::{BinaryOp, UnaryOp};

// DataType and modifiers
pub use data_type::{DataType, RefModifier};

// TypeDef and supporting types
pub use type_def::{
    TypeDef,
    PrimitiveKind,
    Visibility,
    TypeKind,
    ReferenceKind,
    FieldDef,
    MethodSignature,
    PropertyAccessors,
    OperatorBehavior,
};

// FunctionDef and supporting types
pub use function_def::{
    FunctionDef,
    Param,
    FunctionTraits,
    AutoGeneratedMethod,
};

// Expression info
pub use expr_info::ExprInfo;

// Type behaviors
pub use behaviors::TypeBehaviors;

// FFI expressions
pub use ffi_expr::FfiExpr;

// Source location tracking
pub use span::Span;

// Error types
pub use error::{
    AngelScriptError,
    LexError,
    ParseError,
    ParseErrorKind,
    ParseErrors,
    RegistrationError,
    CompilationError,
    RuntimeError,
};

// Native function types
pub use native_fn::{NativeFn, NativeCallable, VmSlot, ObjectHandle, ObjectHeap, CallContext};

// Native error types
pub use native_error::{ConversionError, NativeError};

// List buffer types
pub use list_buffer::{ListBuffer, TupleListBuffer, ListPattern};

// Template types
pub use template::{TemplateInstanceInfo, TemplateValidation};

// Any type support
pub use any_type::{AnyRef, AnyRefMut};

// Unit ID for script compilation units
pub use ids::UnitId;

// Operator enum for proc-macro attributes
pub use operator::Operator;

// Any trait for registrable types
pub use any::Any;

// Registry entry types
pub use entries::{
    // Source tracking
    TypeSource, FunctionSource,
    // Common types
    PropertyEntry, EnumValue,
    // Type entries
    PrimitiveEntry, TemplateParamEntry, EnumEntry, InterfaceEntry,
    FuncdefEntry, ClassEntry,
    // Function entry
    FunctionEntry, FunctionImpl,
    // Unified type entry
    TypeEntry,
    // Global property types
    ConstantValue, GlobalPropertyAccessor, GlobalPropertyEntry, GlobalPropertyImpl,
    IntoGlobalProperty, PropertyError,
};

// Proc-macro metadata types
pub use meta::{
    ClassMeta,
    FunctionMeta,
    PropertyMeta,
    ParamMeta,
    Behavior,
    InterfaceMeta,
    InterfaceMethodMeta,
    FuncdefMeta,
    GlobalMeta,
    // New types for enhanced function metadata
    ReturnMode,
    ReturnMeta,
    GenericParamMeta,
    ListPatternMeta,
};
