//! AngelScript Core Types
//!
//! This crate provides the core type definitions shared between the FFI
//! and compiler crates in the AngelScript implementation.
//!
//! ## Core Types
//!
//! - [`TypeHash`]: Deterministic 64-bit hash for type identity
//! - [`DataType`]: Complete type with modifiers (const, handle, reference)
//! - [`TypeDef`]: Type definitions (primitives, classes, interfaces, enums, funcdefs)
//! - [`FunctionDef`]: Function definitions with complete signatures
//! - [`ExprInfo`]: Expression type checking results
//! - [`TypeBehaviors`]: Lifecycle behaviors for types
//! - [`FfiExpr`]: Owned expressions for FFI default arguments
//! - [`Span`]: Source location tracking for error reporting
//!
//! ## Registry Entry Types
//!
//! - [`TypeEntry`]: Unified enum for type storage in registry
//! - [`ClassEntry`], [`EnumEntry`], [`InterfaceEntry`], [`FuncdefEntry`]: Type entries
//! - [`FunctionEntry`]: Function storage with implementation
//! - [`TypeSource`], [`FunctionSource`]: Origin tracking (FFI vs script)
//!
//! ## Operators
//!
//! - [`BinaryOp`]: Binary operators (arithmetic, logical, comparison)
//! - [`UnaryOp`]: Unary operators (negation, not, increment)
//! - [`Operator`]: Operator enum for proc-macro attributes
//!
//! ## Traits
//!
//! - [`Any`]: Trait for types registrable with AngelScript
//!
//! ## Error Types
//!
//! - [`AngelScriptError`]: Unified error type for all phases
//! - [`LexError`]: Lexer/tokenization errors
//! - [`ParseError`]: Parser errors with [`ParseErrorKind`]
//! - [`ParseErrors`]: Collection of parse errors
//! - [`RegistrationError`]: Type/function registration errors
//! - [`CompilationError`]: Semantic analysis and compilation errors
//! - [`RuntimeError`]: Execution/runtime errors

mod behaviors;
mod data_type;
mod error;
mod function_def;
pub mod ops;
mod span;
mod type_def;
pub mod type_hash;

// New types for unified type registry
mod any;
pub mod entries;
mod ids;
mod operator;

// Native function / VM runtime types (moved from angelscript-registry)
pub mod any_type;
pub mod list_buffer;
pub mod native_error;
pub mod native_fn;
pub mod template;

// Conversion traits for FFI
pub mod convert;

// Metadata types for proc-macros
pub mod meta;

// String factory trait
mod string_factory;

// TypeHash and related
pub use type_hash::{TypeHash, hash_constants, primitives};

// Operators
pub use ops::{BinaryOp, UnaryOp};

// DataType and modifiers
pub use data_type::{DataType, RefModifier};

// TypeDef and supporting types
pub use type_def::{
    FieldDef, MethodSignature, OperatorBehavior, PrimitiveKind, PropertyAccessors, ReferenceKind,
    TypeDef, TypeKind, Visibility,
};

// FunctionDef and supporting types
pub use function_def::{AutoGeneratedMethod, FunctionDef, FunctionTraits, Param};

// Type behaviors
pub use behaviors::{ListBehavior, TypeBehaviors};

// Source location tracking
pub use span::Span;

// Error types
pub use error::{
    AngelScriptError, CompilationError, LexError, ParseError, ParseErrorKind, ParseErrors,
    RegistrationError, RuntimeError,
};

// Native function types
pub use native_fn::{CallContext, Dynamic, NativeCallable, NativeFn, ObjectHandle, ObjectHeap};

// Conversion traits
pub use convert::{FromSlot, IntoSlot};

// Native error types
pub use native_error::{ConversionError, NativeError};

// List buffer types
pub use list_buffer::{ListBuffer, ListPattern, TupleListBuffer};

// Template types
pub use template::{TemplateInstanceInfo, TemplateValidation};

// Any type support
pub use any_type::{AnyRef, AnyRefMut};

// Unit ID for script compilation units
pub use ids::UnitId;

// Operator enum for proc-macro attributes
pub use operator::Operator;

// Any trait for registrable types
pub use any::Any;

// Registry entry types
pub use entries::{
    // Auto-generated function kinds
    AutoGenKind,
    ClassEntry,
    // Global property types
    ConstantValue,
    EnumEntry,
    EnumValue,
    FuncdefEntry,
    // Function entry
    FunctionEntry,
    FunctionImpl,
    FunctionSource,
    GlobalPropertyAccessor,
    GlobalPropertyEntry,
    GlobalPropertyImpl,
    InterfaceEntry,
    IntoGlobalProperty,
    // Type entries
    PrimitiveEntry,
    // Common types
    PropertyEntry,
    PropertyError,
    TemplateParamEntry,
    // Unified type entry
    TypeEntry,
    // Source tracking
    TypeSource,
};

// Proc-macro metadata types
pub use meta::{
    Behavior,
    ClassMeta,
    FuncdefMeta,
    FunctionMeta,
    GenericParamMeta,
    GlobalMeta,
    InterfaceMeta,
    InterfaceMethodMeta,
    ListPatternMeta,
    ParamMeta,
    PropertyMeta,
    ReturnMeta,
    // New types for enhanced function metadata
    ReturnMode,
};

// String factory trait
pub use string_factory::StringFactory;
