coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 85%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 85%
        threshold: 1%
        if_ci_failed: error

comment:
  layout: "header, diff, flags, components, files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
