//! Core type definitions for the compiler.
//!
//! This module re-exports the fundamental type system from `angelscript-core`:
//!
//! - [`TypeHash`]: Deterministic 64-bit hash for type identity
//! - [`DataType`]: Complete type with modifiers (const, handle, reference)
//! - [`TypeDef`]: Type definitions (primitives, classes, interfaces, enums, funcdefs)
//! - [`FunctionDef`]: Function definitions with complete signatures
//! - [`ExprInfo`]: Expression type checking results
//! - [`TypeBehaviors`]: Lifecycle behaviors for types (constructors, factories, etc.)

// Re-export everything from angelscript-core
pub use angelscript_core::{
    // TypeHash and related
    hash_constants, primitives, TypeHash,
    // DataType and modifiers
    DataType, RefModifier,
    // TypeDef and supporting types
    TypeDef, PrimitiveType, Visibility, TypeKind, ReferenceKind,
    FieldDef, MethodSignature, PropertyAccessors, OperatorBehavior,
    // FunctionDef and supporting types
    FunctionDef, Param, FunctionTraits, AutoGeneratedMethod,
    // Expression info
    ExprInfo,
    // Type behaviors
    TypeBehaviors,
    // Operators
    BinaryOp, UnaryOp,
    // FFI expressions
    FfiExpr,
};
