//! Core type definitions for the compiler.
//!
//! This module provides the fundamental type system for the AngelScript compiler:
//!
//! - [`TypeHash`]: Deterministic 64-bit hash for type identity
//! - [`DataType`]: Complete type with modifiers (const, handle, reference)
//! - [`TypeDef`]: Type definitions (primitives, classes, interfaces, enums, funcdefs)
//! - [`FunctionDef`]: Function definitions with complete signatures
//! - [`ExprInfo`]: Expression type checking results
//! - [`TypeBehaviors`]: Lifecycle behaviors for types (constructors, factories, etc.)

pub mod type_hash;
mod data_type;
mod type_def;
mod function_def;
mod expr_info;
mod behaviors;

// TypeHash and related
pub use type_hash::{hash_constants, primitives, TypeHash};

// DataType and modifiers
pub use data_type::{DataType, RefModifier};

// TypeDef and supporting types
pub use type_def::{
    TypeDef,
    PrimitiveType,
    Visibility,
    TypeKind,
    ReferenceKind,
    FieldDef,
    MethodSignature,
    PropertyAccessors,
    OperatorBehavior,
};

// FunctionDef and supporting types
pub use function_def::{
    FunctionDef,
    Param,
    FunctionTraits,
    AutoGeneratedMethod,
};

// Expression info
pub use expr_info::ExprInfo;

// Type behaviors
pub use behaviors::TypeBehaviors;
