//! AngelScript Compiler
//!
//! A clean 2-pass compiler implementation for AngelScript.
//!
//! ## Architecture
//!
//! - **Pass 1 (Registration)**: Register all types and functions with complete signatures
//! - **Pass 2 (Compilation)**: Type check function bodies and generate bytecode
//!
//! ## Modules
//!
//! - [`types`]: Core type definitions (TypeHash, DataType, TypeDef, FunctionDef, ExprInfo, TypeBehaviors)
//! - [`registry`]: Script type and function registry
//! - [`context`]: Compilation context with name resolution
//! - [`passes`]: Compiler passes (registration and compilation)

pub mod types;
pub mod registry;
pub mod context;
pub mod passes;

// Re-export commonly used types for convenience
pub use types::{
    // Core types
    TypeHash, DataType, RefModifier, TypeDef, FunctionDef, ExprInfo, TypeBehaviors,
    // TypeDef supporting types
    PrimitiveType, Visibility, TypeKind, ReferenceKind,
    FieldDef, MethodSignature, PropertyAccessors, OperatorBehavior,
    // FunctionDef supporting types
    Param, FunctionTraits, AutoGeneratedMethod,
    // Operators
    BinaryOp, UnaryOp,
    // FFI expressions
    FfiExpr,
};
pub use registry::{Registry, ScriptRegistry};
pub use context::CompilationContext;
pub use passes::{RegistrationError, RegistrationOutput, RegistrationPass};
