//! Common type definitions shared across the crate.
//!
//! This module contains core type definitions used by both the FFI layer
//! and the semantic analysis layer.
//!
//! # Core Types (from angelscript-core)
//!
//! - [`TypeHash`] - Deterministic 64-bit hash for type identity
//! - [`DataType`] - Complete type with modifiers (const, handle, reference)
//! - [`FfiExpr`] - Owned expressions for default argument values
//!
//! # FFI Registry Types
//!
//! - [`FfiParam`] - Function parameter with resolved DataType
//! - [`FfiFunctionDef`] - Owned function definition for FFI registry
//! - [`FfiPropertyDef`] - Owned property definition for FFI registry
//! - [`FfiTypeDef`] - Owned type (class) definition for FFI registry
//! - [`FfiEnumDef`] - Owned enum definition for FFI registry
//! - [`FfiInterfaceDef`] - Owned interface definition for FFI registry
//! - [`FfiFuncdefDef`] - Owned funcdef (callback type) definition for FFI registry

mod ffi_convert;
mod ffi_enum;
mod ffi_expr;
mod ffi_funcdef;
mod ffi_function;
mod ffi_interface;
mod ffi_property;
mod ffi_type;

// Re-export from angelscript-core
pub use angelscript_core::{
    // TypeHash and related
    hash_constants, primitives as primitive_hashes, TypeHash,
    // DataType and modifiers
    DataType, RefModifier,
    // TypeDef and supporting types
    TypeDef, PrimitiveType, Visibility, TypeKind, ReferenceKind,
    FieldDef, MethodSignature, PropertyAccessors, OperatorBehavior,
    // FunctionDef and supporting types
    FunctionDef, Param, FunctionTraits, AutoGeneratedMethod,
    // Expression info
    ExprInfo,
    // Type behaviors
    TypeBehaviors,
    // Operators
    BinaryOp, UnaryOp,
};

// FFI conversion utilities
pub use ffi_convert::{
    function_param_to_ffi, param_type_to_data_type, return_type_to_data_type, signature_to_ffi_function,
    type_expr_to_data_type,
};

// FFI types
pub use ffi_enum::FfiEnumDef;
pub use ffi_expr::{FfiExpr, FfiExprExt};
pub use ffi_funcdef::FfiFuncdefDef;
pub use ffi_function::{
    FfiFunctionDef, FfiParam, ResolvedFfiFunctionDef, ResolvedFfiParam,
};
pub use ffi_interface::{FfiInterfaceDef, FfiInterfaceMethod};
pub use ffi_property::FfiPropertyDef;
pub use ffi_type::FfiTypeDef;
