//! Type system for AngelScript.
//!
//! This module contains all type-related functionality:
//! - Type definitions (TypeDef)
//! - Runtime data types (DataType)
//! - Script registry (ScriptRegistry) - for script-defined types only
//! - Type conversions (Conversion, ConversionKind)
//! - Type behaviors (TypeBehaviors)
//!
//! FFI types (including primitives) are stored in `FfiRegistry` and accessed
//! via `CompilationContext` which provides a unified lookup interface.
//!
//! ## Type Identity
//!
//! Types are identified by `TypeHash` - a deterministic 64-bit hash computed
//! from the type's qualified name. Primitive type hashes are available in
//! `angelscript_core::primitive_hashes`.

pub mod conversion;
pub mod registry;

// Re-export core types at the top level
pub use angelscript_core::{
    DataType, RefModifier, TypeBehaviors,
    TypeDef, PrimitiveType, Visibility, TypeKind, ReferenceKind,
    FieldDef, MethodSignature, PropertyAccessors, OperatorBehavior,
    FunctionDef as CoreFunctionDef, Param, FunctionTraits, AutoGeneratedMethod,
};

// Semantic-specific types
pub use conversion::{Conversion, ConversionKind, DataTypeExt};
pub use registry::{FunctionDef, GlobalVarDef, ScriptParam, ScriptRegistry};

// Backward-compatible submodule re-exports for existing code
pub mod type_def {
    //! Re-exports of type definition types from angelscript-core.
    pub use angelscript_core::{
        TypeDef, PrimitiveType, Visibility, TypeKind, ReferenceKind,
        FieldDef, MethodSignature, PropertyAccessors, OperatorBehavior,
        FunctionTraits, AutoGeneratedMethod,
    };
}

pub mod data_type {
    //! Re-exports of data type types from angelscript-core.
    pub use angelscript_core::{DataType, RefModifier};
}

pub mod behaviors {
    //! Re-exports of behavior types from angelscript-core.
    pub use angelscript_core::TypeBehaviors;
}
