[package]
name = "example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
angelscript = { path = "../crates/angelscript" }
angelscript_macros = { path = "../crates/angelscript_macros" }