[package]
name = "angelscript"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
angelscript-core.workspace = true
angelscript-lexer.workspace = true
angelscript-parser.workspace = true
angelscript-compiler.workspace = true
angelscript-vm.workspace = true
angelscript-macros.workspace = true
