//! AngelScript Registry crate.
//!
//! This crate provides the unified type and function registry for AngelScript.
//!
//! # Overview
//!
//! The [`SymbolRegistry`] provides central storage for all types and functions:
//!
//! - **Types**: All type entries stored by `TypeHash` for O(1) lookup
//! - **Functions**: All functions (global, methods, operators, behaviors) in one map
//! - **Template Callbacks**: Validation callbacks for template instantiation
//!
//! The [`Module`] type is a container for pending registrations that can be
//! passed to Context for installation.
//!
//! # Example
//!
//! ```
//! use angelscript_registry::SymbolRegistry;
//! use angelscript_core::primitives;
//!
//! let registry = SymbolRegistry::with_primitives();
//! assert!(registry.get(primitives::INT32).is_some());
//! ```
//!
//! # Function Registration
//!
//! Functions are registered using unit structs generated by `#[angelscript::function]`:
//!
//! ```ignore
//! use angelscript_registry::Module;
//!
//! // Free functions - unit struct has original name
//! #[angelscript::function]
//! fn my_func() { }
//!
//! // Methods - use __meta suffix
//! let module = Module::new()
//!     .function(my_func)              // Free function
//!     .function(Type::method__meta);  // Method
//! ```

mod module;
mod namespace_tree;
mod registry;

pub use module::{HasClassMeta, HasFunctionMeta, IntoFunctionMeta, Module};
pub use namespace_tree::{
    NamespaceData, NamespaceEdge, NamespaceTree, ResolutionContext, ResolutionResult,
};
pub use registry::SymbolRegistry;

// Re-export RegistrationError from core
pub use angelscript_core::RegistrationError;

// Re-export from core for backwards compatibility during transition
pub use angelscript_core::{
    // Native function types
    CallContext,
    // Error types
    ConversionError,
    // Core types
    DataType,
    Dynamic,
    // List buffer types
    ListBuffer,
    ListPattern,
    NativeCallable,
    NativeError,
    NativeFn,
    ObjectHandle,
    ObjectHeap,
    RefModifier,
    // Template types
    TemplateInstanceInfo,
    TemplateValidation,
    TupleListBuffer,
    TypeHash,
    TypeKind,
};
